### ISSUE TITLE
from plain ruby to rails

### ISSUE THREAD

**Issue by lnfel** [square/square-ruby-sdk#4]
I am building with Ruby on Rails and now I have this awesome form. I also tested both
[connect v2](https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/rails_payment) and [square-ruby-sdk](https://github.com/square/square-ruby-sdk) then finally decided to stick with square-ruby sdk. I have put the working example into my controller but it shows that client is undefined.
It works on plain ruby tho, did I miss anything. Any tips would be appreciated.
[Screenshots link](https://imgur.com/a/FAxy5z8)

**Comment by havenwood** [comment]
Hi @lnfel. I saw your question was cross-posted to the Square [developer community chat](https://squ.re/slack) and is being answered there, so I'm closing the issue here. Folk in the chat spotted that your client is named `square` but then it's referred to in the code as `client`, as well as other suggestions.
